addSbtPlugin("com.eed3si9n"  % "sbt-assembly"    % "2.3.1")
addSbtPlugin("org.scoverage" % "sbt-scoverage"   % "2.3.0")
addSbtPlugin("org.scalameta" % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix"    % "0.14.0")
addSbtPlugin("com.typesafe"  % "sbt-mima-plugin" % "1.1.4")
